### ISSUE TITLE
Unable to install resourcepacks!

### ISSUE THREAD

**Issue by vanja-san** [Goose-Bomb/GBCLV3#31] opened 2020-03-12 23:49 UTC
### Trying to install resourcepack (any):

```
System.IO.FileNotFoundException: Could not find file 'C:\their.Games\GooseMC\.minecraft\resourcepacks\BlockPixel-JavaEdition-112-Weapons.zip'.
File name: 'C:\their.Games\GooseMC\.minecraft\resourcepacks\BlockPixel-JavaEdition-112-Weapons.zip'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.OpenRead(String archiveFileName)
   at GBCLV3.Services.Auxiliary.ResourcePackService.LoadZip(String path, String[] enabledPackIDs)
   at GBCLV3.Services.Auxiliary.ResourcePackService.<MoveLoadAllAsync>b__5_0(String path)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at GBCLV3.Services.Auxiliary.ResourcePackService.MoveLoadAllAsync(IEnumerable`1 paths)
   at GBCLV3.ViewModels.Tabs.ResourcePackViewModel.AddNew()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[Launcher Version: 3.0.9.104]
```
![2020-03-13-06-40-54](https://user-images.githubusercontent.com/7201687/76576997-7ff95300-64f6-11ea-952a-ab3e9300e94f.png)

**Comment by Goose-Bomb** [comment] 2020-03-14 09:49
A bug caused by my carelessness 😝. I forgot to create the **_resourcepacks_** directory before moving the pack files.
It will be fixed in next release.

**Comment by Goose-Bomb** [comment] 2020-03-14 11:27
Now I first load the resourcepack zip file **_in-place_** the source directory, only if it is a valid resourcepack will I move it into the **_resourcepacks_** directory.

**Comment by vanja-san** [comment] 2020-03-14 15:59
> 
> 
> Now I first load the resourcepack zip file **in-place** the source directory, only if it is a valid resourcepack will I move it into the **_resourcepacks_** directory. This should work.

And how soon to wait for the update 🥺? I look forward to it! 😤

**Closed** 2020-03-21 04:31 UTC
Labels: bug
